### PR TITLE
Remove allow-from directive

### PR DESCRIPTION
**Pull request by danielklecha**
Allow-from is an obsolete directive that no longer works in modern browsers.

### CODE REVIEW

**Comment by bretfourbe** [comment]
Hi @danielklecha, thanks for contributing.
Indeed, according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options, `allow-from` is now deprecated.
What about raising the use of a deprecated value instead of just removing it ?
@devl00p

**Comment by danielklecha** [comment]
@bretfourbe Maybe is_set method should be split into is_set and contains. This could give 3 states:
- is not set => error
- doesn't contain any element from checklist => warning "X-Frame-Options contains invalid value"
- else => success

**Comment by danielklecha** [comment]
@bretfourbe I updated the code and tested it on my machine. Is it ok?

**Comment by bretfourbe** [comment]
I would keep variables for these strings
```python
HSTS_NOT_SET = "Strict-Transport-Security is not set"
XCONTENT_TYPE_NOT_SET = "X-Content-Type-Options is not set"
XFRAME_OPTIONS_NOT_SET = "X-Frame-Options is not set"
``` 
and add the following ones
```python
INVALID_HSTS = "Strict-Transport-Security has an invalid value"
INVALID_XCONTENT_TYPE = "X-Content-Type-Options has an invalid value"
INVALID_XFRAME_OPTIONS = "X-Frame-Options has an invalid value"
``` 
And in check_list change `info` field like this ?
```python
info = {"error": HSTS_NOT_SET, "warning": INVALID_HSTS}
``` 
So you don't need to change `check_header` parameters ?

**Comment by danielklecha** [comment]
@bretfourbe I updated PR based on your suggestions.

**Review by tarraschk — APPROVED** [review]

**Comment by tarraschk** [comment]
The code looks okay for me, thanks for your contribution

@bretfourbe peux-tu regarder si le format de sortie reste identique à ce qu'on produisait auparavant ? C'est important pour qu'on récupère correctement les données dans Cyberwatch

**Comment by bretfourbe** [comment]
Hi @danielklecha, looks good to me !
Can you just fix the coding style issue `wapitiCore/attack/mod_http_headers.py:68:0: C0303: Trailing whitespace (trailing-whitespace)` please ?
Thanks

**Comment by danielklecha** [comment]
@bretfourbe done
Thanks!

**Pull request merged**
