### PR TITLE
Use sslscan in place of sslyze

### PR DESCRIPTION
**Pull request by devl00p**
Theer is still an issue related to certificate transparency logs.

Can't tell at the moment if crt.sh is broken or if I should do things  differently.

### CODE REVIEW

**Comment by devl00p** [comment]
related to https://github.com/wapiti-scanner/wapiti/issues/553

Did a simple check for a pattern in crt.sh responses for CT logs.

**Comment by bretfourbe** [comment]
Hi @devl00p,
I think we should remove `ssl` from `common_modules` here : https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/attack/attack.py#L81 since `sslscan` is not installed by default.

**Comment by devl00p** [comment]
> Hi @devl00p, I think we should remove `ssl` from `common_modules` here : https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/attack/attack.py#L81 since `sslscan` is not installed by default.

Hello,

No, this is on purpose to encourage users to install the dependency. They wil just get a warning telling them to install sslscan.

**Comment by Qwarctick** [comment]
> No, this is on purpose to encourage users to install the dependency. They wil just get a warning telling them to install sslscan.

I does not work. If sslscan is not installed, subprocess will raise a `FileNotFoundError` and stop the execution. You will not have the correct warning.

**Pull request merged**
