### PR TITLE
Add wappalyzer attack module

### PR DESCRIPTION
**Pull request by bretfourbe**
Add wappalyzer attack module :  web technology detection (with versions and categories).
Fix setup.py, Pipefile, MANIFEST.in and attack.py to support the new mod_wapp module.
Fix undefined variable in crawler.py.

### CODE REVIEW

**Comment by fwininger** [comment]
You can not add code in GPLv3 because it's incompatible with the wapiti licence (GPLv2)

**Comment by devl00p** [comment]
> You can not add code in GPLv3 because it's incompatible with the wapiti licence (GPLv2)

I'm not sure they are using GPLv3.

I saw a wappalyzer repo on github using GPLv3 but it seems to be a fork.

From the repository ( https://github.com/aliasio/wappalyzer ) I found from wappalyzer.com it seems that the official one is under MIT so it should be ok to use the json data (I saw no mentions about the json files)

**Comment by devl00p** [comment]
Just make sure the apps.json comes from the repository under MIT

**Comment by fwininger** [comment]
> 
> 
> Just make sure the apps.json comes from the repository under MIT

apps.json is under MIT.

The issue came from the .py file.

**Comment by fwininger** [comment]
and actually we are sure if we want apps.json with 15 000 lines in the repos, because this file change often.

**Comment by devl00p** [comment]
The json file may be dowloaded when the module is first launched, the same way the nikto module works.

Then we may consider adding a --update option to wapiti to sync those files.

Still the python code must comply with GPL v2

**Comment by fwininger** [comment]
> The json file may be dowloaded when the module is first launched, the same way the nikto module works.

We don't want something like this. In our use case we a not able to have internet access at the first launch. We need to include everything in the installation process.

> Still the python code must comply with GPL v2

In progress

**Comment by bretfourbe** [comment]
Hi ! Could you check this one is now ok ?

**Comment by devl00p** [comment]
I'm merging this and I will push some changes on master after ad I'm not yet familiar with pull requests. I made some changes to use Wapiti Page object

**Pull request merged**
