### PR TITLE
Create LICENSE file

### PR DESCRIPTION
**Pull request by fwininger**

### CODE REVIEW

**Comment by devl00p** [comment]
Hello,

There is already a license in doc/COPYING.

Using COPYING as a filename seems common ( https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project ) but I'm open to suggestions on moving the file or renaming it.

**Comment by fwininger** [comment]
@devl00p thanks for the review, I prefer to use the github standard because it's more clear in the web interface to found the licence.

I will change the PR

**Comment by fwininger** [comment]
I found time to update this PR.

According : https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

for github, it's best to have a LICENSE file.

**Comment by fwininger** [comment]
image

**Pull request merged**
